channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - jupyter_client
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_highlight_selected_word
  - jupyter_nbextensions_configurator
  - pip:
    - wget
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.12.2
    - tensorboardx==1.6
    - imutils
    - kapre
    - keras-applications
    - keras-preprocessing
    - librosa
    - python-speech-features
    - soundfile
    - tqdm
